// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etqoynpfhqerdjqmazzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0cW95bnBmaHFlcmRqcW1henpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MDc2NTksImV4cCI6MjA2MjQ4MzY1OX0.WkTGg_8dy0blRKICqAbv28dNbi9WdrkbD4T9kWhLgL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);